project:
  type: website
  output-dir: docs
website:
  title: ""
  navbar:
    left: 
      - text: Home
        href: index.qmd
      # - text: Projects
      #   href: projects.qmd
    right:
      - text: Resume
        href: https://github.com/danielkick/Resume/blob/main/Resume.pdf
      - text: CV
        href: https://github.com/danielkick/Resume/blob/main/Curriculum-Vitae.pdf
      - icon: github
        href: https://github.com/danielkick
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-kick-5a449b9a/
         

  page-footer:
    center: |
      [Contact Daniel](mailto:hello@danielkick.com)
    right: |
      [View the Source](https://github.com/danielkick/danielkick.github.io)
    background: "#2780e3"  
    
    
format:
  html:
    theme: 
       light: [litera, theme_light_custom.scss]
       dark:  [litera, theme_dark_custom.scss]
    code-link: true
    code-fold: false
    code-block-bg: "lightgray"
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    highlight-style: sphinx
    css: styles.css

editor: visual

