---
title: "Genuary 2021"
description: |
  A short description of the post.
author:
  - name: Daniel Kick
    url: https://danielkick.github.io/
date: 01-02-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

```

JAN.1
// TRIPLE NESTED LOOP
```{r}

for (i in 1:3){
  for (j in 1:3){
    for (k in 1:3){
      
      
      
    }
  }
}

```

JAN.2
Rule 30 (elementary cellular automaton)
```{r}
# current pattern 	
# 111 	110 	101 	100 	011 	010 	001 	000
#  0 	   0 	   0 	   1 	   1 	   1 	   1 	   0 # new state for center cell 

rule_30 <- function(current_state = c("0001000")){
  # Locate all the triplets that code for 1 in the next row
  matching_codons <- do.call(
    rbind, 
    stringr::str_locate_all(
      current_state, 
      pattern = c("100",	"011", "010", "001")
    )
  )
  # Create new state
  next_state <- rep(0, times = str_length(current_state)) 
  next_state[matching_codons[, 1]+1] <- 1
  next_state <- paste0(next_state, collapse = "")  
  return(next_state)
}

set.seed(9907334)
iter <- 100
initial_state <- paste0(rbinom(100, size = 1, prob = 0.1), collapse = "")
state_list <- list()
state_list[[1]] <- initial_state
for(i in 1:iter){
  state_list[[length(state_list)+1]] <- rule_30(current_state = state_list[[length(state_list)]])  
}

walk(seq_along(state_list), function(i){
  state_list[[i]] <<- unlist(stringr::str_split(state_list[[i]], pattern = ""))
})

state_df <- as.data.frame(do.call(rbind, state_list))

state_df$Iter <- seq(1, nrow(state_df))-1

gather(state_df, 
       key = "X", value = "Cell", 
       names(state_df)[names(state_df) != "Iter"]) %>% 
  mutate(X = as.numeric(stringr::str_remove(X, "V"))) %>% 
  ggplot(aes(x=X, y = Iter, fill = Cell))+
  geom_tile()+
  scale_y_reverse()+
  scale_fill_brewer()+
  theme_minimal()+
  theme(legend.position = "")
```







```{r}
# logistic map

r = 1

growth_fcn <- function(r = 1, x0 = 1){return(x1 = (r*x0)*(1-x0))}


data.frame(x0 = seq(-0.1, 1.1, length.out = 50)) %>% 
  mutate("0"   = growth_fcn(r = 0,   x0 = x0),
         "0.5" = growth_fcn(r = 0.5, x0 = x0),
         "1"   = growth_fcn(r = 1,   x0 = x0),
         "1.5" = growth_fcn(r = 1.5, x0 = x0),
         "2"   = growth_fcn(r = 2,   x0 = x0)
         ) %>% 
  gather("r", "x1", as.character(c(0, .5, 1, 1.5, 2))) %>% 
  ggplot()+
  geom_line(aes(x = x0, y = x1, color = r))


iter = 10

M <- data.frame(Start = seq(0, 1, length.out = 20))
M <- cbind(M, as.data.frame(matrix(NA, nrow= nrow(M), ncol = iter)))

for (COL in 2:ncol(M)){
  M[,COL] <- growth_fcn(x0 = M[,COL-1])
}

M <- M %>% 
   mutate(V0 = Start) %>% 
  mutate(Start = as.factor(Start)) %>% 
   gather(Iter, Value, starts_with("V")) %>% 
   mutate(Iter = as.numeric(str_remove(Iter, "V")))



M %>% 
  ggplot(aes(x = Iter, y = Value, color = Start))+
  geom_line()




```

